[workspace]
members = [".", "codegen"]


[package]
name = "solangp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = { version = "0.1.0", path = "./codegen" }
